name: Generate Jar and deploy it to AWS Beanstalk
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Jar file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code for operations
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate static site and production jar
        run : mvn clean install
      - name: Zip the jar for deployment
        run: zip deploy.zip ./target/amin-0.0.1-SNAPSHOT.jar


      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: aminsennour.com 4.0
          environment_name: Aminsennourcom40-env
          version_label: 12345
          region: us-west-2
          deployment_package: deploy.zip