name: Generate Jar and deploy it to AWS Beanstalk
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Jar file
    runs-on: ubuntu-latest
    steps:
      - Name: Checkout Repo Code for operations
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - Name: Generate static site and production jar
      - run : mvn clean install